// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiawfPySiFhyz_ZfoGKbSP8KzFddIpOZU',
    appId: '1:637276184592:web:2298fd0c34d349e5cf6a95',
    messagingSenderId: '637276184592',
    projectId: 'intricue-3804f',
    authDomain: 'intricue-3804f.firebaseapp.com',
    storageBucket: 'intricue-3804f.firebasestorage.app',
    measurementId: 'G-QNBDYS8JDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCocApPSSOcXOQ0ZQi5po0mCVNTUkGlVg',
    appId: '1:637276184592:android:e869f09c0d9d7ccecf6a95',
    messagingSenderId: '637276184592',
    projectId: 'intricue-3804f',
    storageBucket: 'intricue-3804f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAxYe3kiHfi5YHo_AByJ-NL4bhLFP4Do',
    appId: '1:637276184592:ios:07c8a78d3ac94bdacf6a95',
    messagingSenderId: '637276184592',
    projectId: 'intricue-3804f',
    storageBucket: 'intricue-3804f.firebasestorage.app',
    iosBundleId: 'com.example.intricueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAxYe3kiHfi5YHo_AByJ-NL4bhLFP4Do',
    appId: '1:637276184592:ios:07c8a78d3ac94bdacf6a95',
    messagingSenderId: '637276184592',
    projectId: 'intricue-3804f',
    storageBucket: 'intricue-3804f.firebasestorage.app',
    iosBundleId: 'com.example.intricueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiawfPySiFhyz_ZfoGKbSP8KzFddIpOZU',
    appId: '1:637276184592:web:12408a0964332530cf6a95',
    messagingSenderId: '637276184592',
    projectId: 'intricue-3804f',
    authDomain: 'intricue-3804f.firebaseapp.com',
    storageBucket: 'intricue-3804f.firebasestorage.app',
    measurementId: 'G-6PDL1E4HCN',
  );
}
